import java.util.Arrays;
import java.util.HashSet;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
//    public boolean someLibraryMethod() {
//        return true;
//    }
public static void main(String[] args) {
    int[][] weeklyMonthTemperatures = {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}
    };

    int[] ans = roll(4);
    System.out.println(Arrays.toString(ans));
    System.out.println(containsDuplicates(ans));
    System.out.println(avg(ans));
}
    public static int[] roll(int n ) {
    int[] thing =  new int[n];
    for (int i = 0; i < n; i++){
        thing[i] = (int)(Math.random() *((6 -1 ) +1 )) +1;
    }
    return thing;
    }

    public static boolean containsDuplicates (int[] ans){
    for (int i = 0; i < ans.length; i++){
        for (int j = i + 1; j < ans.length; j++){
            if (ans[i] == ans[j]) {
                return true;
            }
        }
    }
        return false;
    }

    public static int avg (int[] ans){
    int sum = 0;
    for (int i = 0; i <= ans.length - 1; i++ ){
        sum = sum + ans[i];
    }
   return sum / ans.length;
    }

    public static void analyzingWeatherData(int[][] weeklyMonthTemperatures) {
    HashSet<Integer> tempature = new HashSet<>();
    int highest = weeklyMonthTemperatures[0][0];
    int min = weeklyMonthTemperatures[0][0];

    //declare hash set

    for (int i=0; i < weeklyMonthTemperatures.length; i++){
        for (int j =0; j < weeklyMonthTemperatures[i].length; j++){
            if (weeklyMonthTemperatures[i][j] > highest){
                highest = weeklyMonthTemperatures[i][j];
            }
            if (weeklyMonthTemperatures[i][j] < min){
                min = weeklyMonthTemperatures[i][j];
            }
        }
    }

    }
}
