import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
            Path imagePath = FileSystems.getDefault().getPath("resources", "test.BMP");

            bitmap bmp = new bitmap(imagePath);

            bmp.flipVertically();

            bmp.save(FileSystems.getDefault().getPath("resources", "test_new.BMP"));
        }

    }

